#############################
# AUTOGENERATED FROM TEMPLATE
#############################

%define debug_package %{nil}
%define user {{user}}
%define group {{group}}

Name:    {{name}}
Version: {{version}}
Release: 1%{?dist}
Summary: {{summary}}
License: {{license}}
URL:     {{URL}}

{%- for source in sources %}
Source{{loop.index - 1}}: {{source}}
{%- endfor %}

%{?systemd_requires}
Requires(pre): shadow-utils

%description

{{description}}

%prep
%setup -q -n %{name}-%{version}.linux-amd64

%build
{{build}}

%install
{{install}}

%pre
{{pre}}

%post
{{post}}

%preun
{{preun}}

%postun
{{postun}}

%files
{{files}}
