#############################
# AUTOGENERATED FROM TEMPLATE
#############################

%define debug_package %{nil}
%define user {{user}}
%define group {{group}}

Name:    {{name}}
Version: {{version}}
Release: 1%{?dist}
Summary: {{summary}}
License: {{license}}
URL:     {{URL}}

{%- for source in sources %}
Source{{loop.index - 1}}: {{source}}
{%- endfor %}

%{?systemd_requires}
Requires(pre): shadow-utils
%if 0%{?el6} || 0%{?el5}
Requires(post): chkconfig
Requires(preun): chkconfig
# This is for /sbin/service
Requires(preun): initscripts
%endif

%description
{{description}}

%prep
{{prep}}

%build
{{build}}

%install
{{install}}

%pre
{{pre}}

%post
{{post}}

%preun
{{preun}}

%postun
{{postun}}

%files
{{files}}
